// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.sourceforge.gjtapi.raw.remote;

public final class RemoteProviderImpl_Stub
    extends java.rmi.server.RemoteStub
    implements net.sourceforge.gjtapi.raw.remote.RemoteProvider, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addListener_0;
    private static java.lang.reflect.Method $method_allocateMedia_1;
    private static java.lang.reflect.Method $method_answerCall_2;
    private static java.lang.reflect.Method $method_attachMedia_3;
    private static java.lang.reflect.Method $method_beep_4;
    private static java.lang.reflect.Method $method_createCall_5;
    private static java.lang.reflect.Method $method_freeMedia_6;
    private static java.lang.reflect.Method $method_getAddressType_7;
    private static java.lang.reflect.Method $method_getAddresses_8;
    private static java.lang.reflect.Method $method_getAddresses_9;
    private static java.lang.reflect.Method $method_getCall_10;
    private static java.lang.reflect.Method $method_getCallsOnAddress_11;
    private static java.lang.reflect.Method $method_getCallsOnTerminal_12;
    private static java.lang.reflect.Method $method_getCapabilities_13;
    private static java.lang.reflect.Method $method_getDialledDigits_14;
    private static java.lang.reflect.Method $method_getPrivateData_15;
    private static java.lang.reflect.Method $method_getTerminals_16;
    private static java.lang.reflect.Method $method_getTerminals_17;
    private static java.lang.reflect.Method $method_hold_18;
    private static java.lang.reflect.Method $method_initialize_19;
    private static java.lang.reflect.Method $method_isMediaTerminal_20;
    private static java.lang.reflect.Method $method_join_21;
    private static java.lang.reflect.Method $method_play_22;
    private static java.lang.reflect.Method $method_record_23;
    private static java.lang.reflect.Method $method_release_24;
    private static java.lang.reflect.Method $method_releaseCallId_25;
    private static java.lang.reflect.Method $method_removeListener_26;
    private static java.lang.reflect.Method $method_reportCallsOnAddress_27;
    private static java.lang.reflect.Method $method_reportCallsOnTerminal_28;
    private static java.lang.reflect.Method $method_reserveCallId_29;
    private static java.lang.reflect.Method $method_retrieveSignals_30;
    private static java.lang.reflect.Method $method_sendPrivateData_31;
    private static java.lang.reflect.Method $method_sendSignals_32;
    private static java.lang.reflect.Method $method_setLoadControl_33;
    private static java.lang.reflect.Method $method_setPrivateData_34;
    private static java.lang.reflect.Method $method_shutdown_35;
    private static java.lang.reflect.Method $method_stop_36;
    private static java.lang.reflect.Method $method_stopReportingCall_37;
    private static java.lang.reflect.Method $method_triggerRTC_38;
    private static java.lang.reflect.Method $method_unHold_39;
    
    static {
	try {
	    $method_addListener_0 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("addListener", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.RemoteListener.class});
	    $method_allocateMedia_1 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("allocateMedia", new java.lang.Class[] {java.lang.String.class, int.class, java.util.Dictionary.class});
	    $method_answerCall_2 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("answerCall", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class});
	    $method_attachMedia_3 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("attachMedia", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, boolean.class});
	    $method_beep_4 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("beep", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class});
	    $method_createCall_5 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("createCall", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, java.lang.String.class});
	    $method_freeMedia_6 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("freeMedia", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_getAddressType_7 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getAddressType", new java.lang.Class[] {java.lang.String.class});
	    $method_getAddresses_8 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getAddresses", new java.lang.Class[] {});
	    $method_getAddresses_9 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getAddresses", new java.lang.Class[] {java.lang.String.class});
	    $method_getCall_10 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getCall", new java.lang.Class[] {net.sourceforge.gjtapi.CallId.class});
	    $method_getCallsOnAddress_11 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getCallsOnAddress", new java.lang.Class[] {java.lang.String.class});
	    $method_getCallsOnTerminal_12 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getCallsOnTerminal", new java.lang.Class[] {java.lang.String.class});
	    $method_getCapabilities_13 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getCapabilities", new java.lang.Class[] {});
	    $method_getDialledDigits_14 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getDialledDigits", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class});
	    $method_getPrivateData_15 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getPrivateData", new java.lang.Class[] {net.sourceforge.gjtapi.CallId.class, java.lang.String.class, java.lang.String.class});
	    $method_getTerminals_16 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getTerminals", new java.lang.Class[] {});
	    $method_getTerminals_17 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("getTerminals", new java.lang.Class[] {java.lang.String.class});
	    $method_hold_18 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("hold", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class});
	    $method_initialize_19 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("initialize", new java.lang.Class[] {java.util.Map.class});
	    $method_isMediaTerminal_20 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("isMediaTerminal", new java.lang.Class[] {java.lang.String.class});
	    $method_join_21 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("join", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class});
	    $method_play_22 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("play", new java.lang.Class[] {java.lang.String.class, java.lang.String[].class, int.class, net.sourceforge.gjtapi.media.RTCHolder[].class, java.util.Dictionary.class});
	    $method_record_23 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("record", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, net.sourceforge.gjtapi.media.RTCHolder[].class, java.util.Dictionary.class});
	    $method_release_24 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("release", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.raw.remote.SerializableCallId.class});
	    $method_releaseCallId_25 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("releaseCallId", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class});
	    $method_removeListener_26 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("removeListener", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.RemoteListener.class});
	    $method_reportCallsOnAddress_27 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("reportCallsOnAddress", new java.lang.Class[] {java.lang.String.class, boolean.class});
	    $method_reportCallsOnTerminal_28 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("reportCallsOnTerminal", new java.lang.Class[] {java.lang.String.class, boolean.class});
	    $method_reserveCallId_29 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("reserveCallId", new java.lang.Class[] {java.lang.String.class});
	    $method_retrieveSignals_30 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("retrieveSignals", new java.lang.Class[] {java.lang.String.class, int.class, net.sourceforge.gjtapi.media.SymbolHolder[].class, net.sourceforge.gjtapi.media.RTCHolder[].class, java.util.Dictionary.class});
	    $method_sendPrivateData_31 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("sendPrivateData", new java.lang.Class[] {net.sourceforge.gjtapi.CallId.class, java.lang.String.class, java.lang.String.class, java.io.Serializable.class});
	    $method_sendSignals_32 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("sendSignals", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder[].class, net.sourceforge.gjtapi.media.RTCHolder[].class, java.util.Dictionary.class});
	    $method_setLoadControl_33 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("setLoadControl", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, double.class, double.class, double.class, int[].class});
	    $method_setPrivateData_34 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("setPrivateData", new java.lang.Class[] {net.sourceforge.gjtapi.CallId.class, java.lang.String.class, java.lang.String.class, java.io.Serializable.class});
	    $method_shutdown_35 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("shutdown", new java.lang.Class[] {});
	    $method_stop_36 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("stop", new java.lang.Class[] {java.lang.String.class});
	    $method_stopReportingCall_37 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("stopReportingCall", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class});
	    $method_triggerRTC_38 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("triggerRTC", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder.class});
	    $method_unHold_39 = net.sourceforge.gjtapi.raw.remote.RemoteProvider.class.getMethod("unHold", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteProviderImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addListener(RemoteListener)
    public void addListener(net.sourceforge.gjtapi.raw.remote.RemoteListener $param_RemoteListener_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addListener_0, new java.lang.Object[] {$param_RemoteListener_1}, -18193135659330897L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of allocateMedia(String, int, Dictionary)
    public boolean allocateMedia(java.lang.String $param_String_1, int $param_int_2, java.util.Dictionary $param_Dictionary_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_allocateMedia_1, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2), $param_Dictionary_3}, 2533523714532311180L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of answerCall(SerializableCallId, String, String)
    public void answerCall(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    ref.invoke(this, $method_answerCall_2, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3}, -8837493149565496836L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of attachMedia(SerializableCallId, String, boolean)
    public boolean attachMedia(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_attachMedia_3, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Boolean($param_boolean_3)}, 7427139849288102212L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of beep(SerializableCallId)
    public void beep(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_beep_4, new java.lang.Object[] {$param_SerializableCallId_1}, -791690703264378229L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of createCall(SerializableCallId, String, String, String)
    public net.sourceforge.gjtapi.raw.remote.SerializableCallId createCall(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.lang.String $param_String_4)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException, javax.telephony.InvalidPartyException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    Object $result = ref.invoke(this, $method_createCall_5, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, $param_String_4}, 245752182603459960L);
	    return ((net.sourceforge.gjtapi.raw.remote.SerializableCallId) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (javax.telephony.InvalidPartyException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of freeMedia(String, int)
    public boolean freeMedia(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_freeMedia_6, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 3043732216997857144L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAddressType(String)
    public int getAddressType(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAddressType_7, new java.lang.Object[] {$param_String_1}, 4378886913802166480L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAddresses()
    public java.lang.String[] getAddresses()
	throws java.rmi.RemoteException, javax.telephony.ResourceUnavailableException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAddresses_8, null, -7386168852153787696L);
	    return ((java.lang.String[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getAddresses(String)
    public java.lang.String[] getAddresses(java.lang.String $param_String_1)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException
    {
	try {
	    Object $result = ref.invoke(this, $method_getAddresses_9, new java.lang.Object[] {$param_String_1}, -2204285425132514162L);
	    return ((java.lang.String[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCall(CallId)
    public net.sourceforge.gjtapi.CallData getCall(net.sourceforge.gjtapi.CallId $param_CallId_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCall_10, new java.lang.Object[] {$param_CallId_1}, 4751359150934435500L);
	    return ((net.sourceforge.gjtapi.CallData) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCallsOnAddress(String)
    public net.sourceforge.gjtapi.CallData[] getCallsOnAddress(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCallsOnAddress_11, new java.lang.Object[] {$param_String_1}, -6311383443143617746L);
	    return ((net.sourceforge.gjtapi.CallData[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCallsOnTerminal(String)
    public net.sourceforge.gjtapi.CallData[] getCallsOnTerminal(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCallsOnTerminal_12, new java.lang.Object[] {$param_String_1}, 491881163826283491L);
	    return ((net.sourceforge.gjtapi.CallData[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getCapabilities()
    public java.util.Properties getCapabilities()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getCapabilities_13, null, -2415022597185156558L);
	    return ((java.util.Properties) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDialledDigits(SerializableCallId, String)
    public java.lang.String getDialledDigits(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDialledDigits_14, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2}, 4282882863050450017L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPrivateData(CallId, String, String)
    public java.io.Serializable getPrivateData(net.sourceforge.gjtapi.CallId $param_CallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.io.NotSerializableException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPrivateData_15, new java.lang.Object[] {$param_CallId_1, $param_String_2, $param_String_3}, -5981086972446446512L);
	    return ((java.io.Serializable) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.io.NotSerializableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTerminals()
    public net.sourceforge.gjtapi.TermData[] getTerminals()
	throws java.rmi.RemoteException, javax.telephony.ResourceUnavailableException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTerminals_16, null, 4627927307509478851L);
	    return ((net.sourceforge.gjtapi.TermData[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTerminals(String)
    public net.sourceforge.gjtapi.TermData[] getTerminals(java.lang.String $param_String_1)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTerminals_17, new java.lang.Object[] {$param_String_1}, -2311689262549722456L);
	    return ((net.sourceforge.gjtapi.TermData[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of hold(SerializableCallId, String, String)
    public void hold(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    ref.invoke(this, $method_hold_18, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3}, 5589684156383560639L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of initialize(Map)
    public void initialize(java.util.Map $param_Map_1)
	throws java.rmi.RemoteException, javax.telephony.ProviderUnavailableException
    {
	try {
	    ref.invoke(this, $method_initialize_19, new java.lang.Object[] {$param_Map_1}, 926939022245481607L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of isMediaTerminal(String)
    public boolean isMediaTerminal(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_isMediaTerminal_20, new java.lang.Object[] {$param_String_1}, -1743179532067850802L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of join(SerializableCallId, SerializableCallId, String, String)
    public net.sourceforge.gjtapi.CallId join(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_2, java.lang.String $param_String_3, java.lang.String $param_String_4)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    Object $result = ref.invoke(this, $method_join_21, new java.lang.Object[] {$param_SerializableCallId_1, $param_SerializableCallId_2, $param_String_3, $param_String_4}, 8917435358731897344L);
	    return ((net.sourceforge.gjtapi.CallId) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of play(String, String[], int, RTCHolder[], Dictionary)
    public void play(java.lang.String $param_String_1, java.lang.String[] $param_arrayOf_String_2, int $param_int_3, net.sourceforge.gjtapi.media.RTCHolder[] $param_arrayOf_RTCHolder_4, java.util.Dictionary $param_Dictionary_5)
	throws java.rmi.RemoteException, javax.telephony.media.MediaResourceException
    {
	try {
	    ref.invoke(this, $method_play_22, new java.lang.Object[] {$param_String_1, $param_arrayOf_String_2, new java.lang.Integer($param_int_3), $param_arrayOf_RTCHolder_4, $param_Dictionary_5}, -2066987364880548900L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.media.MediaResourceException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of record(String, String, RTCHolder[], Dictionary)
    public void record(java.lang.String $param_String_1, java.lang.String $param_String_2, net.sourceforge.gjtapi.media.RTCHolder[] $param_arrayOf_RTCHolder_3, java.util.Dictionary $param_Dictionary_4)
	throws java.rmi.RemoteException, javax.telephony.media.MediaResourceException
    {
	try {
	    ref.invoke(this, $method_record_23, new java.lang.Object[] {$param_String_1, $param_String_2, $param_arrayOf_RTCHolder_3, $param_Dictionary_4}, 2513176167022823853L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.media.MediaResourceException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of release(String, SerializableCallId)
    public void release(java.lang.String $param_String_1, net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_2)
	throws java.rmi.RemoteException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    ref.invoke(this, $method_release_24, new java.lang.Object[] {$param_String_1, $param_SerializableCallId_2}, -5068360126875562952L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of releaseCallId(SerializableCallId)
    public void releaseCallId(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_releaseCallId_25, new java.lang.Object[] {$param_SerializableCallId_1}, -2166011456959580773L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeListener(RemoteListener)
    public void removeListener(net.sourceforge.gjtapi.raw.remote.RemoteListener $param_RemoteListener_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeListener_26, new java.lang.Object[] {$param_RemoteListener_1}, -5875059931331494611L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of reportCallsOnAddress(String, boolean)
    public void reportCallsOnAddress(java.lang.String $param_String_1, boolean $param_boolean_2)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException, javax.telephony.ResourceUnavailableException
    {
	try {
	    ref.invoke(this, $method_reportCallsOnAddress_27, new java.lang.Object[] {$param_String_1, new java.lang.Boolean($param_boolean_2)}, 3751208898059149039L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of reportCallsOnTerminal(String, boolean)
    public void reportCallsOnTerminal(java.lang.String $param_String_1, boolean $param_boolean_2)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException, javax.telephony.ResourceUnavailableException
    {
	try {
	    ref.invoke(this, $method_reportCallsOnTerminal_28, new java.lang.Object[] {$param_String_1, new java.lang.Boolean($param_boolean_2)}, 9006200389776332348L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of reserveCallId(String)
    public net.sourceforge.gjtapi.raw.remote.SerializableCallId reserveCallId(java.lang.String $param_String_1)
	throws java.rmi.RemoteException, javax.telephony.InvalidArgumentException
    {
	try {
	    Object $result = ref.invoke(this, $method_reserveCallId_29, new java.lang.Object[] {$param_String_1}, -6436779848245437758L);
	    return ((net.sourceforge.gjtapi.raw.remote.SerializableCallId) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.InvalidArgumentException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of retrieveSignals(String, int, SymbolHolder[], RTCHolder[], Dictionary)
    public net.sourceforge.gjtapi.RawSigDetectEvent retrieveSignals(java.lang.String $param_String_1, int $param_int_2, net.sourceforge.gjtapi.media.SymbolHolder[] $param_arrayOf_SymbolHolder_3, net.sourceforge.gjtapi.media.RTCHolder[] $param_arrayOf_RTCHolder_4, java.util.Dictionary $param_Dictionary_5)
	throws java.rmi.RemoteException, javax.telephony.media.MediaResourceException
    {
	try {
	    Object $result = ref.invoke(this, $method_retrieveSignals_30, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2), $param_arrayOf_SymbolHolder_3, $param_arrayOf_RTCHolder_4, $param_Dictionary_5}, 3977026443323767797L);
	    return ((net.sourceforge.gjtapi.RawSigDetectEvent) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.media.MediaResourceException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sendPrivateData(CallId, String, String, Serializable)
    public java.io.Serializable sendPrivateData(net.sourceforge.gjtapi.CallId $param_CallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.io.Serializable $param_Serializable_4)
	throws java.io.NotSerializableException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sendPrivateData_31, new java.lang.Object[] {$param_CallId_1, $param_String_2, $param_String_3, $param_Serializable_4}, -282139160852120049L);
	    return ((java.io.Serializable) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.io.NotSerializableException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sendSignals(String, SymbolHolder[], RTCHolder[], Dictionary)
    public void sendSignals(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder[] $param_arrayOf_SymbolHolder_2, net.sourceforge.gjtapi.media.RTCHolder[] $param_arrayOf_RTCHolder_3, java.util.Dictionary $param_Dictionary_4)
	throws java.rmi.RemoteException, javax.telephony.media.MediaResourceException
    {
	try {
	    ref.invoke(this, $method_sendSignals_32, new java.lang.Object[] {$param_String_1, $param_arrayOf_SymbolHolder_2, $param_arrayOf_RTCHolder_3, $param_Dictionary_4}, -8015219492964444907L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.media.MediaResourceException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setLoadControl(String, String, double, double, double, int[])
    public void setLoadControl(java.lang.String $param_String_1, java.lang.String $param_String_2, double $param_double_3, double $param_double_4, double $param_double_5, int[] $param_arrayOf_int_6)
	throws java.rmi.RemoteException, javax.telephony.MethodNotSupportedException
    {
	try {
	    ref.invoke(this, $method_setLoadControl_33, new java.lang.Object[] {$param_String_1, $param_String_2, new java.lang.Double($param_double_3), new java.lang.Double($param_double_4), new java.lang.Double($param_double_5), $param_arrayOf_int_6}, 6968357235220805123L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setPrivateData(CallId, String, String, Serializable)
    public void setPrivateData(net.sourceforge.gjtapi.CallId $param_CallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.io.Serializable $param_Serializable_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setPrivateData_34, new java.lang.Object[] {$param_CallId_1, $param_String_2, $param_String_3, $param_Serializable_4}, 2812373702278809629L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of shutdown()
    public void shutdown()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_shutdown_35, null, -7207851917985848402L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of stop(String)
    public void stop(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_stop_36, new java.lang.Object[] {$param_String_1}, -1941243546222654391L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of stopReportingCall(SerializableCallId)
    public boolean stopReportingCall(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_stopReportingCall_37, new java.lang.Object[] {$param_SerializableCallId_1}, -4063301108072956014L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of triggerRTC(String, SymbolHolder)
    public void triggerRTC(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder $param_SymbolHolder_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_triggerRTC_38, new java.lang.Object[] {$param_String_1, $param_SymbolHolder_2}, -4152761879276781553L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of unHold(SerializableCallId, String, String)
    public void unHold(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException, javax.telephony.MethodNotSupportedException, javax.telephony.PrivilegeViolationException, javax.telephony.ResourceUnavailableException, net.sourceforge.gjtapi.RawStateException
    {
	try {
	    ref.invoke(this, $method_unHold_39, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3}, 2948511455472052859L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.telephony.MethodNotSupportedException e) {
	    throw e;
	} catch (javax.telephony.PrivilegeViolationException e) {
	    throw e;
	} catch (javax.telephony.ResourceUnavailableException e) {
	    throw e;
	} catch (net.sourceforge.gjtapi.RawStateException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
