// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.sourceforge.gjtapi.raw.remote;

public final class RemoteListenerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements net.sourceforge.gjtapi.raw.remote.RemoteListener, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addressPrivateData_0;
    private static java.lang.reflect.Method $method_callActive_1;
    private static java.lang.reflect.Method $method_callInvalid_2;
    private static java.lang.reflect.Method $method_callOverloadCeased_3;
    private static java.lang.reflect.Method $method_callOverloadEncountered_4;
    private static java.lang.reflect.Method $method_callPrivateData_5;
    private static java.lang.reflect.Method $method_connectionAddressAnalyse_6;
    private static java.lang.reflect.Method $method_connectionAddressCollect_7;
    private static java.lang.reflect.Method $method_connectionAlerting_8;
    private static java.lang.reflect.Method $method_connectionAuthorizeCallAttempt_9;
    private static java.lang.reflect.Method $method_connectionCallDelivery_10;
    private static java.lang.reflect.Method $method_connectionConnected_11;
    private static java.lang.reflect.Method $method_connectionDisconnected_12;
    private static java.lang.reflect.Method $method_connectionFailed_13;
    private static java.lang.reflect.Method $method_connectionInProgress_14;
    private static java.lang.reflect.Method $method_connectionSuspended_15;
    private static java.lang.reflect.Method $method_mediaPlayPause_16;
    private static java.lang.reflect.Method $method_mediaPlayResume_17;
    private static java.lang.reflect.Method $method_mediaRecorderPause_18;
    private static java.lang.reflect.Method $method_mediaRecorderResume_19;
    private static java.lang.reflect.Method $method_mediaSignalDetectorDetected_20;
    private static java.lang.reflect.Method $method_mediaSignalDetectorOverflow_21;
    private static java.lang.reflect.Method $method_mediaSignalDetectorPatternMatched_22;
    private static java.lang.reflect.Method $method_providerPrivateData_23;
    private static java.lang.reflect.Method $method_terminalConnectionCreated_24;
    private static java.lang.reflect.Method $method_terminalConnectionDropped_25;
    private static java.lang.reflect.Method $method_terminalConnectionHeld_26;
    private static java.lang.reflect.Method $method_terminalConnectionRinging_27;
    private static java.lang.reflect.Method $method_terminalConnectionTalking_28;
    private static java.lang.reflect.Method $method_terminalPrivateData_29;
    
    static {
	try {
	    $method_addressPrivateData_0 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("addressPrivateData", new java.lang.Class[] {java.lang.String.class, java.io.Serializable.class, int.class});
	    $method_callActive_1 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("callActive", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, int.class});
	    $method_callInvalid_2 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("callInvalid", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, int.class});
	    $method_callOverloadCeased_3 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("callOverloadCeased", new java.lang.Class[] {java.lang.String.class});
	    $method_callOverloadEncountered_4 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("callOverloadEncountered", new java.lang.Class[] {java.lang.String.class});
	    $method_callPrivateData_5 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("callPrivateData", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.io.Serializable.class, int.class});
	    $method_connectionAddressAnalyse_6 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionAddressAnalyse", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionAddressCollect_7 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionAddressCollect", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionAlerting_8 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionAlerting", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionAuthorizeCallAttempt_9 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionAuthorizeCallAttempt", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionCallDelivery_10 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionCallDelivery", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionConnected_11 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionConnected", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionDisconnected_12 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionDisconnected", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionFailed_13 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionFailed", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionInProgress_14 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionInProgress", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_connectionSuspended_15 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("connectionSuspended", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, int.class});
	    $method_mediaPlayPause_16 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaPlayPause", new java.lang.Class[] {java.lang.String.class, int.class, int.class, net.sourceforge.gjtapi.media.SymbolHolder.class});
	    $method_mediaPlayResume_17 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaPlayResume", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder.class});
	    $method_mediaRecorderPause_18 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaRecorderPause", new java.lang.Class[] {java.lang.String.class, int.class, net.sourceforge.gjtapi.media.SymbolHolder.class});
	    $method_mediaRecorderResume_19 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaRecorderResume", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder.class});
	    $method_mediaSignalDetectorDetected_20 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaSignalDetectorDetected", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder[].class});
	    $method_mediaSignalDetectorOverflow_21 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaSignalDetectorOverflow", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder[].class});
	    $method_mediaSignalDetectorPatternMatched_22 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("mediaSignalDetectorPatternMatched", new java.lang.Class[] {java.lang.String.class, net.sourceforge.gjtapi.media.SymbolHolder[].class, int.class});
	    $method_providerPrivateData_23 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("providerPrivateData", new java.lang.Class[] {java.io.Serializable.class, int.class});
	    $method_terminalConnectionCreated_24 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalConnectionCreated", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, int.class});
	    $method_terminalConnectionDropped_25 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalConnectionDropped", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, int.class});
	    $method_terminalConnectionHeld_26 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalConnectionHeld", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, int.class});
	    $method_terminalConnectionRinging_27 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalConnectionRinging", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, int.class});
	    $method_terminalConnectionTalking_28 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalConnectionTalking", new java.lang.Class[] {net.sourceforge.gjtapi.raw.remote.SerializableCallId.class, java.lang.String.class, java.lang.String.class, int.class});
	    $method_terminalPrivateData_29 = net.sourceforge.gjtapi.raw.remote.RemoteListener.class.getMethod("terminalPrivateData", new java.lang.Class[] {java.lang.String.class, java.io.Serializable.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteListenerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addressPrivateData(String, Serializable, int)
    public void addressPrivateData(java.lang.String $param_String_1, java.io.Serializable $param_Serializable_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addressPrivateData_0, new java.lang.Object[] {$param_String_1, $param_Serializable_2, new java.lang.Integer($param_int_3)}, -3261087373176657345L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of callActive(SerializableCallId, int)
    public void callActive(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callActive_1, new java.lang.Object[] {$param_SerializableCallId_1, new java.lang.Integer($param_int_2)}, -7473625328124764482L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of callInvalid(SerializableCallId, int)
    public void callInvalid(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callInvalid_2, new java.lang.Object[] {$param_SerializableCallId_1, new java.lang.Integer($param_int_2)}, 8626750289955177557L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of callOverloadCeased(String)
    public void callOverloadCeased(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callOverloadCeased_3, new java.lang.Object[] {$param_String_1}, -1902337848684749321L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of callOverloadEncountered(String)
    public void callOverloadEncountered(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callOverloadEncountered_4, new java.lang.Object[] {$param_String_1}, 5871156801106079223L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of callPrivateData(SerializableCallId, Serializable, int)
    public void callPrivateData(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.io.Serializable $param_Serializable_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_callPrivateData_5, new java.lang.Object[] {$param_SerializableCallId_1, $param_Serializable_2, new java.lang.Integer($param_int_3)}, 514101569967957082L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionAddressAnalyse(SerializableCallId, String, int)
    public void connectionAddressAnalyse(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionAddressAnalyse_6, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -3740076425284357062L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionAddressCollect(SerializableCallId, String, int)
    public void connectionAddressCollect(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionAddressCollect_7, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -8633034329271714949L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionAlerting(SerializableCallId, String, int)
    public void connectionAlerting(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionAlerting_8, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -2374978473229901864L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionAuthorizeCallAttempt(SerializableCallId, String, int)
    public void connectionAuthorizeCallAttempt(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionAuthorizeCallAttempt_9, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -1992406747323686903L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionCallDelivery(SerializableCallId, String, int)
    public void connectionCallDelivery(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionCallDelivery_10, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -3179910411135250898L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionConnected(SerializableCallId, String, int)
    public void connectionConnected(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionConnected_11, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -3754294142881119695L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionDisconnected(SerializableCallId, String, int)
    public void connectionDisconnected(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionDisconnected_12, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -2534372091270235040L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionFailed(SerializableCallId, String, int)
    public void connectionFailed(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionFailed_13, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, 6722101853842274972L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionInProgress(SerializableCallId, String, int)
    public void connectionInProgress(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionInProgress_14, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -1269056968879542242L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionSuspended(SerializableCallId, String, int)
    public void connectionSuspended(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_connectionSuspended_15, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, new java.lang.Integer($param_int_3)}, -1221701057095179734L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaPlayPause(String, int, int, SymbolHolder)
    public void mediaPlayPause(java.lang.String $param_String_1, int $param_int_2, int $param_int_3, net.sourceforge.gjtapi.media.SymbolHolder $param_SymbolHolder_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaPlayPause_16, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2), new java.lang.Integer($param_int_3), $param_SymbolHolder_4}, -5844722152829784521L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaPlayResume(String, SymbolHolder)
    public void mediaPlayResume(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder $param_SymbolHolder_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaPlayResume_17, new java.lang.Object[] {$param_String_1, $param_SymbolHolder_2}, 4972373004390224239L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaRecorderPause(String, int, SymbolHolder)
    public void mediaRecorderPause(java.lang.String $param_String_1, int $param_int_2, net.sourceforge.gjtapi.media.SymbolHolder $param_SymbolHolder_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaRecorderPause_18, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2), $param_SymbolHolder_3}, -8063656750448937465L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaRecorderResume(String, SymbolHolder)
    public void mediaRecorderResume(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder $param_SymbolHolder_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaRecorderResume_19, new java.lang.Object[] {$param_String_1, $param_SymbolHolder_2}, -4628885275422271100L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaSignalDetectorDetected(String, SymbolHolder[])
    public void mediaSignalDetectorDetected(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder[] $param_arrayOf_SymbolHolder_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaSignalDetectorDetected_20, new java.lang.Object[] {$param_String_1, $param_arrayOf_SymbolHolder_2}, -7735992635563467181L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaSignalDetectorOverflow(String, SymbolHolder[])
    public void mediaSignalDetectorOverflow(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder[] $param_arrayOf_SymbolHolder_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaSignalDetectorOverflow_21, new java.lang.Object[] {$param_String_1, $param_arrayOf_SymbolHolder_2}, -2573654265839254032L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of mediaSignalDetectorPatternMatched(String, SymbolHolder[], int)
    public void mediaSignalDetectorPatternMatched(java.lang.String $param_String_1, net.sourceforge.gjtapi.media.SymbolHolder[] $param_arrayOf_SymbolHolder_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_mediaSignalDetectorPatternMatched_22, new java.lang.Object[] {$param_String_1, $param_arrayOf_SymbolHolder_2, new java.lang.Integer($param_int_3)}, 4864612432133709031L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of providerPrivateData(Serializable, int)
    public void providerPrivateData(java.io.Serializable $param_Serializable_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_providerPrivateData_23, new java.lang.Object[] {$param_Serializable_1, new java.lang.Integer($param_int_2)}, 4872754382205226235L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalConnectionCreated(SerializableCallId, String, String, int)
    public void terminalConnectionCreated(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalConnectionCreated_24, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, new java.lang.Integer($param_int_4)}, 6715036410187952870L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalConnectionDropped(SerializableCallId, String, String, int)
    public void terminalConnectionDropped(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalConnectionDropped_25, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, new java.lang.Integer($param_int_4)}, 6871996706161039699L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalConnectionHeld(SerializableCallId, String, String, int)
    public void terminalConnectionHeld(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalConnectionHeld_26, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, new java.lang.Integer($param_int_4)}, 5856516063284866044L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalConnectionRinging(SerializableCallId, String, String, int)
    public void terminalConnectionRinging(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalConnectionRinging_27, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, new java.lang.Integer($param_int_4)}, -1459210378458556853L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalConnectionTalking(SerializableCallId, String, String, int)
    public void terminalConnectionTalking(net.sourceforge.gjtapi.raw.remote.SerializableCallId $param_SerializableCallId_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalConnectionTalking_28, new java.lang.Object[] {$param_SerializableCallId_1, $param_String_2, $param_String_3, new java.lang.Integer($param_int_4)}, -7812812857564409055L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of terminalPrivateData(String, Serializable, int)
    public void terminalPrivateData(java.lang.String $param_String_1, java.io.Serializable $param_Serializable_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_terminalPrivateData_29, new java.lang.Object[] {$param_String_1, $param_Serializable_2, new java.lang.Integer($param_int_3)}, 5803541372268291418L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
