/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl */

#ifndef _Included_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
#define _Included_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3Init
 * Signature: (Ljava/util/Map;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3Init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3Shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3Shutdown
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3AnswerCall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3AnswerCall
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3DisconnectCall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3DisconnectCall
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3ReleaseCall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3ReleaseCall
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3ReserveCallId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3ReserveCallId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3CreateCall
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3CreateCall
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3Dial
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3Dial
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3Hold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3Hold
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3Join
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3Join
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3UnHold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3UnHold
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl
 * Method:    tapi3SendSignals
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_gjtapi_raw_tapi3_Tapi3NativeImpl_tapi3SendSignals
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
