package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/_CorbaListenerImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public abstract class _CorbaListenerImplBase extends org.omg.CORBA.portable.ObjectImpl implements CorbaListener, org.omg.CORBA.portable.InvokeHandler {
  private static java.util.Hashtable _methods = new java.util.Hashtable ();

  static
  {
	_methods.put ("addressPrivateData", new java.lang.Integer (0));
	_methods.put ("callActive", new java.lang.Integer (1));
	_methods.put ("callInvalid", new java.lang.Integer (2));
	_methods.put ("callPrivateData", new java.lang.Integer (3));
	_methods.put ("callOverloadCeased", new java.lang.Integer (4));
	_methods.put ("callOverloadEncountered", new java.lang.Integer (5));
	_methods.put ("connectionAddressAnalyse", new java.lang.Integer (6));
	_methods.put ("connectionAddressCollect", new java.lang.Integer (7));
	_methods.put ("connectionAlerting", new java.lang.Integer (8));
	_methods.put ("connectionAuthorizeCallAttempt", new java.lang.Integer (9));
	_methods.put ("connectionCallDelivery", new java.lang.Integer (10));
	_methods.put ("connectionConnected", new java.lang.Integer (11));
	_methods.put ("connectionDisconnected", new java.lang.Integer (12));
	_methods.put ("connectionFailed", new java.lang.Integer (13));
	_methods.put ("connectionInProgress", new java.lang.Integer (14));
	_methods.put ("connectionSuspended", new java.lang.Integer (15));
	_methods.put ("mediaPlayPause", new java.lang.Integer (16));
	_methods.put ("mediaPlayResume", new java.lang.Integer (17));
	_methods.put ("mediaRecorderPause", new java.lang.Integer (18));
	_methods.put ("mediaRecorderResume", new java.lang.Integer (19));
	_methods.put ("mediaSDDetected", new java.lang.Integer (20));
	_methods.put ("mediaSDOverflow", new java.lang.Integer (21));
	_methods.put ("mediaSDPatternMatched", new java.lang.Integer (22));
	_methods.put ("providerPrivateData", new java.lang.Integer (23));
	_methods.put ("terminalConnectionCreated", new java.lang.Integer (24));
	_methods.put ("terminalConnectionDropped", new java.lang.Integer (25));
	_methods.put ("terminalConnectionHeld", new java.lang.Integer (26));
	_methods.put ("terminalConnectionRinging", new java.lang.Integer (27));
	_methods.put ("terminalConnectionTalking", new java.lang.Integer (28));
	_methods.put ("terminalPrivateData", new java.lang.Integer (29));
  }
  // Type-specific CORBA::Object operations
  private static String[] __ids = {
	"IDL:com/uforce/jtapi/generic/raw/remote/corba/CorbaListener:1.0"};
  // Constructors
  public _CorbaListenerImplBase ()
  {
  }      
  public String[] _ids ()
  {
	return __ids;
  }      
  public org.omg.CORBA.portable.OutputStream _invoke (String method,
								org.omg.CORBA.portable.InputStream in,
								org.omg.CORBA.portable.ResponseHandler rh)
  {
	org.omg.CORBA.portable.OutputStream out = null;
	java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
	if (__method == null)
	  throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

	switch (__method.intValue ())
	{
	   case 0:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/addressPrivateData
	   {
		 String address = in.read_string ();
		 org.omg.CORBA.Any data = in.read_any ();
		 int cause = in.read_long ();
		 this.addressPrivateData (address, data, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 1:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/callActive
	   {
		 int callId = in.read_long ();
		 int cause = in.read_long ();
		 this.callActive (callId, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 2:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/callInvalid
	   {
		 int callId = in.read_long ();
		 int cause = in.read_long ();
		 this.callInvalid (callId, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 3:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/callPrivateData
	   {
		 int callId = in.read_long ();
		 org.omg.CORBA.Any data = in.read_any ();
		 int cause = in.read_long ();
		 this.callPrivateData (callId, data, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 4:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/callOverloadCeased
	   {
		 String address = in.read_string ();
		 this.callOverloadCeased (address);
		 out = rh.createReply();
		 break;
	   }

	   case 5:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/callOverloadEncountered
	   {
		 String address = in.read_string ();
		 this.callOverloadEncountered (address);
		 out = rh.createReply();
		 break;
	   }

	   case 6:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionAddressAnalyse
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionAddressAnalyse (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 7:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionAddressCollect
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionAddressCollect (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 8:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionAlerting
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionAlerting (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 9:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionAuthorizeCallAttempt
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionAuthorizeCallAttempt (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 10:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionCallDelivery
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionCallDelivery (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 11:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionConnected
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionConnected (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 12:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionDisconnected
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionDisconnected (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 13:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionFailed
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionFailed (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 14:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionInProgress
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionInProgress (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 15:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/connectionSuspended
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 int cause = in.read_long ();
		 this.connectionSuspended (callId, address, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 16:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaPlayPause
	   {
		 String terminal = in.read_string ();
		 int index = in.read_long ();
		 int offset = in.read_long ();
		 int trigger = in.read_long ();
		 this.mediaPlayPause (terminal, index, offset, trigger);
		 out = rh.createReply();
		 break;
	   }

	   case 17:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaPlayResume
	   {
		 String terminal = in.read_string ();
		 int trigger = in.read_long ();
		 this.mediaPlayResume (terminal, trigger);
		 out = rh.createReply();
		 break;
	   }

	   case 18:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaRecorderPause
	   {
		 String terminal = in.read_string ();
		 int duration = in.read_long ();
		 int trigger = in.read_long ();
		 this.mediaRecorderPause (terminal, duration, trigger);
		 out = rh.createReply();
		 break;
	   }

	   case 19:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaRecorderResume
	   {
		 String terminal = in.read_string ();
		 int trigger = in.read_long ();
		 this.mediaRecorderResume (terminal, trigger);
		 out = rh.createReply();
		 break;
	   }

	   case 20:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaSDDetected
	   {
		 String terminal = in.read_string ();
		 int sigs[] = net.sourceforge.gjtapi.raw.remote.corba.LongArrayHelper.read (in);
		 this.mediaSDDetected (terminal, sigs);
		 out = rh.createReply();
		 break;
	   }

	   case 21:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaSDOverflow
	   {
		 String terminal = in.read_string ();
		 int sigs[] = net.sourceforge.gjtapi.raw.remote.corba.LongArrayHelper.read (in);
		 this.mediaSDOverflow (terminal, sigs);
		 out = rh.createReply();
		 break;
	   }

	   case 22:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/mediaSDPatternMatched
	   {
		 String terminal = in.read_string ();
		 int sigs[] = net.sourceforge.gjtapi.raw.remote.corba.LongArrayHelper.read (in);
		 int index = in.read_long ();
		 this.mediaSDPatternMatched (terminal, sigs, index);
		 out = rh.createReply();
		 break;
	   }

	   case 23:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/providerPrivateData
	   {
		 org.omg.CORBA.Any data = in.read_any ();
		 int cause = in.read_long ();
		 this.providerPrivateData (data, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 24:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalConnectionCreated
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 String terminal = in.read_string ();
		 int cause = in.read_long ();
		 this.terminalConnectionCreated (callId, address, terminal, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 25:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalConnectionDropped
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 String terminal = in.read_string ();
		 int cause = in.read_long ();
		 this.terminalConnectionDropped (callId, address, terminal, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 26:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalConnectionHeld
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 String terminal = in.read_string ();
		 int cause = in.read_long ();
		 this.terminalConnectionHeld (callId, address, terminal, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 27:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalConnectionRinging
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 String terminal = in.read_string ();
		 int cause = in.read_long ();
		 this.terminalConnectionRinging (callId, address, terminal, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 28:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalConnectionTalking
	   {
		 int callId = in.read_long ();
		 String address = in.read_string ();
		 String terminal = in.read_string ();
		 int cause = in.read_long ();
		 this.terminalConnectionTalking (callId, address, terminal, cause);
		 out = rh.createReply();
		 break;
	   }

	   case 29:  // com/uforce/jtapi/generic/raw/remote/corba/CorbaListener/terminalPrivateData
	   {
		 String terminal = in.read_string ();
		 org.omg.CORBA.Any data = in.read_any ();
		 int cause = in.read_long ();
		 this.terminalPrivateData (terminal, data, cause);
		 out = rh.createReply();
		 break;
	   }

	   default:
		 throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
	}

	return out;
  } // _invoke        
} // class _CorbaListenerImplBase
