package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/CallData.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class CallData implements org.omg.CORBA.portable.IDLEntity
{
	static final long serialVersionUID = 6550666207749062382L;
	
  public int callId = (int)0;
  public int state = (int)0;
  public net.sourceforge.gjtapi.raw.remote.corba.ConnectionData connections[] = null;

  public CallData ()
  {
  } // ctor      
  public CallData (int _callId, int _state, net.sourceforge.gjtapi.raw.remote.corba.ConnectionData[] _connections)
  {
	callId = _callId;
	state = _state;
	connections = _connections;
  } // ctor        
} // class CallData
