package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/ConnectionData.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class ConnectionData implements org.omg.CORBA.portable.IDLEntity
{
	static final long serialVersionUID = 5313094066932619440L;
	
  public int state = (int)0;
  public String address = null;
  public boolean isLocal = false;
  public net.sourceforge.gjtapi.raw.remote.corba.TCData tcs[] = null;

  public ConnectionData ()
  {
  } // ctor      
  public ConnectionData (int _state, String _address, boolean _isLocal, net.sourceforge.gjtapi.raw.remote.corba.TCData[] _tcs)
  {
	state = _state;
	address = _address;
	isLocal = _isLocal;
	tcs = _tcs;
  } // ctor        
} // class ConnectionData
