package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/CorbaListenerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public interface CorbaListenerOperations 
{
  void addressPrivateData (String address, org.omg.CORBA.Any data, int cause);      
  void callActive (int callId, int cause);      
  void callInvalid (int callId, int cause);      
  void callOverloadCeased (String address);      
  void callOverloadEncountered (String address);      
  void callPrivateData (int callId, org.omg.CORBA.Any data, int cause);      
  void connectionAddressAnalyse (int callId, String address, int cause);      
  void connectionAddressCollect (int callId, String address, int cause);      
  void connectionAlerting (int callId, String address, int cause);      
  void connectionAuthorizeCallAttempt (int callId, String address, int cause);      
  void connectionCallDelivery (int callId, String address, int cause);      
  void connectionConnected (int callId, String address, int cause);      
  void connectionDisconnected (int callId, String address, int cause);      
  void connectionFailed (int callId, String address, int cause);      
  void connectionInProgress (int callId, String address, int cause);      
  void connectionSuspended (int callId, String address, int cause);      
  void mediaPlayPause (String terminal, int index, int offset, int trigger);      
  void mediaPlayResume (String terminal, int trigger);      
  void mediaRecorderPause (String terminal, int duration, int trigger);      
  void mediaRecorderResume (String terminal, int trigger);      
  void mediaSDDetected (String terminal, int[] sigs);      
  void mediaSDOverflow (String terminal, int[] sigs);      
  void mediaSDPatternMatched (String terminal, int[] sigs, int index);      
  void providerPrivateData (org.omg.CORBA.Any data, int cause);      
  void terminalConnectionCreated (int callId, String address, String terminal, int cause);      
  void terminalConnectionDropped (int callId, String address, String terminal, int cause);      
  void terminalConnectionHeld (int callId, String address, String terminal, int cause);      
  void terminalConnectionRinging (int callId, String address, String terminal, int cause);      
  void terminalConnectionTalking (int callId, String address, String terminal, int cause);      
  void terminalPrivateData (String terminal, org.omg.CORBA.Any data, int cause);      
} // interface CorbaListenerOperations
