package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/CorbaProviderOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public interface CorbaProviderOperations {
/**
 * 
 * @param cl net.sourceforge.gjtapi.raw.remote.corba.CorbaListener
 */
void addListener(CorbaListener cl);
/**
 * 
 * @return boolean
 * @param term java.lang.String
 * @param type int
 * @param parameters net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 */
boolean allocateMedia(java.lang.String term, int type, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] parameters);
/**
 * 
 * @param callId int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
void answerCall(int callId, java.lang.String address, java.lang.String terminal) throws ResourceUnavailableEx, PrivilegeViolationEx, RawStateEx, MethodNotSupportedEx;
  boolean attachMedia (int call, String address, boolean onFlag);      
  void beep (int call);      
/**
 * 
 * @return int
 * @param callId int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @param destination java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidPartyEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
int createCall(int callId, java.lang.String address, java.lang.String terminal, java.lang.String destination) throws ResourceUnavailableEx, InvalidArgumentEx, InvalidPartyEx, PrivilegeViolationEx, RawStateEx, MethodNotSupportedEx;
  boolean freeMedia (String terminal, int type);      
/**
 * 
 * @return java.lang.String[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 */
java.lang.String[] getAddresses() throws ResourceUnavailableEx;
/**
 * 
 * @return java.lang.String[]
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 */
java.lang.String[] getAddressesForTerm(java.lang.String terminal) throws InvalidArgumentEx;
  int getAddressType (String name);        
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.CallData
 * @param callId int
 */
CallData getCall(int callId);
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.CallData[]
 * @param address java.lang.String
 */
net.sourceforge.gjtapi.raw.remote.corba.CallData[] getCallsOnAddress(java.lang.String address);
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.CallData[]
 * @param terminal java.lang.String
 */
net.sourceforge.gjtapi.raw.remote.corba.CallData[] getCallsOnTerminal(java.lang.String terminal);
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.StringEntry[]
 */
net.sourceforge.gjtapi.raw.remote.corba.StringEntry[] getCapabilities();
  String getDialledDigits (int id, String address);      
/**
 * 
 * @return org.omg.CORBA.Any
 * @param callId int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.NotSerializableEx The exception description.
 */
org.omg.CORBA.Any getPrivateData(int callId, java.lang.String address, java.lang.String terminal) throws NotSerializableEx;
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.TermData[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 */
net.sourceforge.gjtapi.raw.remote.corba.TermData[] getTerminals() throws ResourceUnavailableEx;
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.TermData[]
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 */
net.sourceforge.gjtapi.raw.remote.corba.TermData[] getTerminalsForAddr(java.lang.String terminal) throws InvalidArgumentEx;
/**
 * 
 * @param callId int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
void hold(int callId, java.lang.String address, java.lang.String terminal) throws ResourceUnavailableEx, PrivilegeViolationEx, RawStateEx, MethodNotSupportedEx;
/**
 * 
 * @param props net.sourceforge.gjtapi.raw.remote.corba.StringEntry[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ProviderUnavailableEx The exception description.
 */
void initialize(net.sourceforge.gjtapi.raw.remote.corba.StringEntry[] props) throws ProviderUnavailableEx;
  boolean isMediaTerminal (String terminal);      
/**
 * 
 * @return int
 * @param callId1 int
 * @param callId2 int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
int join(int callId1, int callId2, java.lang.String address, java.lang.String terminal) throws ResourceUnavailableEx, PrivilegeViolationEx, InvalidArgumentEx, RawStateEx, MethodNotSupportedEx;
/**
 * 
 * @param terminal java.lang.String
 * @param streamIds java.lang.String[]
 * @param offset int
 * @param rtcs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @param optArgs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MediaResourceEx The exception description.
 */
void play(java.lang.String terminal, java.lang.String[] streamIds, int offset, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] rtcs, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] optArgs) throws MediaResourceEx;
/**
 * 
 * @param terminal java.lang.String
 * @param streamId java.lang.String
 * @param rtcs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @param optArgs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MediaResourceEx The exception description.
 */
void record(java.lang.String terminal, java.lang.String streamId, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] rtcs, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] optArgs) throws MediaResourceEx;
/**
 * 
 * @param address java.lang.String
 * @param callId int
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
void release(java.lang.String address, int callId) throws ResourceUnavailableEx, PrivilegeViolationEx, RawStateEx, MethodNotSupportedEx;
  void releaseCallId (int callId);      
/**
 * 
 * @param cl net.sourceforge.gjtapi.raw.remote.corba.CorbaListener
 */
void removeListener(CorbaListener cl);
/**
 * 
 * @param address java.lang.String
 * @param flag boolean
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 */
void reportCallsOnAddress(java.lang.String address, boolean flag) throws ResourceUnavailableEx, InvalidArgumentEx;
/**
 * 
 * @param terminal java.lang.String
 * @param flag boolean
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 */
void reportCallsOnTerminal(java.lang.String terminal, boolean flag) throws ResourceUnavailableEx, InvalidArgumentEx;
/**
 * 
 * @return int
 * @param address java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.InvalidArgumentEx The exception description.
 */
int reserveCallId(java.lang.String address) throws InvalidArgumentEx;
/**
 * 
 * @return net.sourceforge.gjtapi.raw.remote.corba.DetectEvent
 * @param terminal java.lang.String
 * @param num int
 * @param patterns int[]
 * @param rtcs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @param optArgs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MediaResourceEx The exception description.
 */
DetectEvent retrieveSignals(java.lang.String terminal, int num, int[] patterns, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] rtcs, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] optArgs) throws MediaResourceEx;
/**
 * 
 * @return org.omg.CORBA.Any
 * @param callId int
 * @param address java.lang.String
 * @param terminal java.lang.String
 * @param data org.omg.CORBA.Any
 * @exception net.sourceforge.gjtapi.raw.remote.corba.NotSerializableEx The exception description.
 */
org.omg.CORBA.Any sendPrivateData(int callId, java.lang.String address, java.lang.String terminal, org.omg.CORBA.Any data) throws NotSerializableEx;
/**
 * 
 * @param terminal java.lang.String
 * @param syms int[]
 * @param rtcs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @param optArgs net.sourceforge.gjtapi.raw.remote.corba.LongEntry[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MediaResourceEx The exception description.
 */
void sendSignals(java.lang.String terminal, int[] syms, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] rtcs, net.sourceforge.gjtapi.raw.remote.corba.LongEntry[] optArgs) throws MediaResourceEx;
/**
 * 
 * @param startAddr java.lang.String
 * @param endAddr java.lang.String
 * @param duration double
 * @param admissionRate double
 * @param interval double
 * @param treatment int[]
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
void setLoadControl(java.lang.String startAddr, java.lang.String endAddr, double duration, double admissionRate, double interval, int[] treatment) throws MethodNotSupportedEx;
  void setPrivateData (int callId, String address, String terminal, org.omg.CORBA.Any data);      
  void shutdown ();      
  void stop (String terminal);      
  boolean stopReportingCall (int callId);      
  void triggerRTC (String terminal, int action);      
/**
 * 
 * @param callId int
 * @param address java.lang.String
 * @param term java.lang.String
 * @exception net.sourceforge.gjtapi.raw.remote.corba.ResourceUnavailableEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.PrivilegeViolationEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.RawStateEx The exception description.
 * @exception net.sourceforge.gjtapi.raw.remote.corba.MethodNotSupportedEx The exception description.
 */
void unHold(int callId, java.lang.String address, java.lang.String term) throws ResourceUnavailableEx, PrivilegeViolationEx, RawStateEx, MethodNotSupportedEx;
}
