package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/CorbaListener.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public interface CorbaListener extends CorbaListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
}
