package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/InvalidPartyEx.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class InvalidPartyEx extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public int type = (int)0;
  public String reason = null;

  public InvalidPartyEx ()
  {
  } // ctor      
  public InvalidPartyEx (int _type, String _reason)
  {
	type = _type;
	reason = _reason;
  } // ctor      
} // class InvalidPartyEx
