package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/MediaResourceEx.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class MediaResourceEx extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String reason = null;
  public net.sourceforge.gjtapi.raw.remote.corba.ResourceEvent event = null;

  public MediaResourceEx ()
  {
  } // ctor      
  public MediaResourceEx (String _reason, net.sourceforge.gjtapi.raw.remote.corba.ResourceEvent _event)
  {
	reason = _reason;
	event = _event;
  } // ctor        
} // class MediaResourceEx
