package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/MethodNotSupportedEx.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class MethodNotSupportedEx extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String reason = null;

  public MethodNotSupportedEx ()
  {
  } // ctor      
  public MethodNotSupportedEx (String _reason)
  {
	reason = _reason;
  } // ctor      
} // class MethodNotSupportedEx
