package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/PlayerEventHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

abstract public class PlayerEventHelper
{
  private static String  _id = "IDL:com/uforce/jtapi/generic/raw/remote/corba/PlayerEvent:1.0";

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  public static net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent extract (org.omg.CORBA.Any a)
  {
	return read (a.create_input_stream ());
  }        
  public static String id ()
  {
	return _id;
  }      
  public static void insert (org.omg.CORBA.Any a, net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent that)
  {
	org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
	a.type (type ());
	write (out, that);
	a.read_value (out.create_input_stream (), type ());
  }        
  public static net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent read (org.omg.CORBA.portable.InputStream istream)
  {
	net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent value = new net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent ();
	value.change = istream.read_long ();
	value.index = istream.read_long ();
	value.offset = istream.read_long ();
	return value;
  }        
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
	if (__typeCode == null)
	{
	  synchronized (org.omg.CORBA.TypeCode.class)
	  {
		if (__typeCode == null)
		{
		  if (__active)
		  {
			return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
		  }
		  __active = true;
		  org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
		  org.omg.CORBA.TypeCode _tcOf_members0 = null;
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[0] = new org.omg.CORBA.StructMember (
			"change",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[1] = new org.omg.CORBA.StructMember (
			"index",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[2] = new org.omg.CORBA.StructMember (
			"offset",
			_tcOf_members0,
			null);
		  __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (net.sourceforge.gjtapi.raw.remote.corba.PlayerEventHelper.id (), "PlayerEvent", _members0);
		  __active = false;
		}
	  }
	}
	return __typeCode;
  }        
  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.sourceforge.gjtapi.raw.remote.corba.PlayerEvent value)
  {
	ostream.write_long (value.change);
	ostream.write_long (value.index);
	ostream.write_long (value.offset);
  }        
}
