package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/PlayerEvent.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class PlayerEvent implements org.omg.CORBA.portable.IDLEntity
{
  public int change = (int)0;
  public int index = (int)0;
  public int offset = (int)0;

  public PlayerEvent ()
  {
  } // ctor      
  public PlayerEvent (int _change, int _index, int _offset)
  {
	change = _change;
	index = _index;
	offset = _offset;
  } // ctor      
} // class PlayerEvent
