package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/RawStateExHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

abstract public class RawStateExHelper
{
  private static String  _id = "IDL:com/uforce/jtapi/generic/raw/remote/corba/RawStateEx:1.0";

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  public static net.sourceforge.gjtapi.raw.remote.corba.RawStateEx extract (org.omg.CORBA.Any a)
  {
	return read (a.create_input_stream ());
  }        
  public static String id ()
  {
	return _id;
  }      
  public static void insert (org.omg.CORBA.Any a, net.sourceforge.gjtapi.raw.remote.corba.RawStateEx that)
  {
	org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
	a.type (type ());
	write (out, that);
	a.read_value (out.create_input_stream (), type ());
  }        
  public static net.sourceforge.gjtapi.raw.remote.corba.RawStateEx read (org.omg.CORBA.portable.InputStream istream)
  {
	net.sourceforge.gjtapi.raw.remote.corba.RawStateEx value = new net.sourceforge.gjtapi.raw.remote.corba.RawStateEx ();
	// read and discard the repository ID
	istream.read_string ();
	value.callId = istream.read_long ();
	value.address = istream.read_string ();
	value.terminal = istream.read_string ();
	value.type = istream.read_long ();
	value.state = istream.read_long ();
	value.info = istream.read_string ();
	return value;
  }        
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
	if (__typeCode == null)
	{
	  synchronized (org.omg.CORBA.TypeCode.class)
	  {
		if (__typeCode == null)
		{
		  if (__active)
		  {
			return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
		  }
		  __active = true;
		  org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
		  org.omg.CORBA.TypeCode _tcOf_members0 = null;
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[0] = new org.omg.CORBA.StructMember (
			"callId",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
		  _members0[1] = new org.omg.CORBA.StructMember (
			"address",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
		  _members0[2] = new org.omg.CORBA.StructMember (
			"terminal",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[3] = new org.omg.CORBA.StructMember (
			"type",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
		  _members0[4] = new org.omg.CORBA.StructMember (
			"state",
			_tcOf_members0,
			null);
		  _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
		  _members0[5] = new org.omg.CORBA.StructMember (
			"info",
			_tcOf_members0,
			null);
		  __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (net.sourceforge.gjtapi.raw.remote.corba.RawStateExHelper.id (), "RawStateEx", _members0);
		  __active = false;
		}
	  }
	}
	return __typeCode;
  }        
  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.sourceforge.gjtapi.raw.remote.corba.RawStateEx value)
  {
	// write the repository ID
	ostream.write_string (id ());
	ostream.write_long (value.callId);
	ostream.write_string (value.address);
	ostream.write_string (value.terminal);
	ostream.write_long (value.type);
	ostream.write_long (value.state);
	ostream.write_string (value.info);
  }        
}
