package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/RecorderEvent.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class RecorderEvent implements org.omg.CORBA.portable.IDLEntity
{
  public int duration = (int)0;

  public RecorderEvent ()
  {
  } // ctor      
  public RecorderEvent (int _duration)
  {
	duration = _duration;
  } // ctor      
} // class RecorderEvent
