package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/ResourceEvent.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class ResourceEvent implements org.omg.CORBA.portable.IDLEntity
{
  public int error = (int)0;
  public int eventId = (int)0;
  public String terminal = null;
  public int qualifier = (int)0;
  public int trigger = (int)0;
  public net.sourceforge.gjtapi.raw.remote.corba.ResourceUnion resUnion = null;

  public ResourceEvent ()
  {
  } // ctor      
  public ResourceEvent (int _error, int _eventId, String _terminal, int _qualifier, int _trigger, net.sourceforge.gjtapi.raw.remote.corba.ResourceUnion _resUnion)
  {
	error = _error;
	eventId = _eventId;
	terminal = _terminal;
	qualifier = _qualifier;
	trigger = _trigger;
	resUnion = _resUnion;
  } // ctor        
} // class ResourceEvent
