package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/ResourceType.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public class ResourceType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static net.sourceforge.gjtapi.raw.remote.corba.ResourceType[] __array = new net.sourceforge.gjtapi.raw.remote.corba.ResourceType [__size];

  public static final int _player = 0;
  public static final net.sourceforge.gjtapi.raw.remote.corba.ResourceType player = new net.sourceforge.gjtapi.raw.remote.corba.ResourceType(_player);
  public static final int _recorder = 1;
  public static final net.sourceforge.gjtapi.raw.remote.corba.ResourceType recorder = new net.sourceforge.gjtapi.raw.remote.corba.ResourceType(_recorder);
  public static final int _sigGenerator = 2;
  public static final net.sourceforge.gjtapi.raw.remote.corba.ResourceType sigGenerator = new net.sourceforge.gjtapi.raw.remote.corba.ResourceType(_sigGenerator);
  public static final int _sigDetector = 3;
  public static final net.sourceforge.gjtapi.raw.remote.corba.ResourceType sigDetector = new net.sourceforge.gjtapi.raw.remote.corba.ResourceType(_sigDetector);

  protected ResourceType (int value)
  {
	__value = value;
	__array[__value] = this;
  }      
  public static net.sourceforge.gjtapi.raw.remote.corba.ResourceType from_int (int value)
  {
	if (value >= 0 && value < __size)
	  return __array[value];
	else
	  throw new org.omg.CORBA.BAD_PARAM ();
  }        
  public int value ()
  {
	return __value;
  }      
} // class ResourceType
