package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/ResourceTypeHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

abstract public class ResourceTypeHelper
{
  private static String  _id = "IDL:com/uforce/jtapi/generic/raw/remote/corba/ResourceType:1.0";

  private static org.omg.CORBA.TypeCode __typeCode = null;
  public static net.sourceforge.gjtapi.raw.remote.corba.ResourceType extract (org.omg.CORBA.Any a)
  {
	return read (a.create_input_stream ());
  }        
  public static String id ()
  {
	return _id;
  }      
  public static void insert (org.omg.CORBA.Any a, net.sourceforge.gjtapi.raw.remote.corba.ResourceType that)
  {
	org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
	a.type (type ());
	write (out, that);
	a.read_value (out.create_input_stream (), type ());
  }        
  public static net.sourceforge.gjtapi.raw.remote.corba.ResourceType read (org.omg.CORBA.portable.InputStream istream)
  {
	return net.sourceforge.gjtapi.raw.remote.corba.ResourceType.from_int (istream.read_long ());
  }        
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
	if (__typeCode == null)
	{
	  __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (net.sourceforge.gjtapi.raw.remote.corba.ResourceTypeHelper.id (), "ResourceType", new String[] { "player", "recorder", "sigGenerator", "sigDetector"} );
	}
	return __typeCode;
  }        
  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.sourceforge.gjtapi.raw.remote.corba.ResourceType value)
  {
	ostream.write_long (value.value ());
  }        
}
