package net.sourceforge.gjtapi.raw.remote.corba;

/**
* com/uforce/jtapi/generic/raw/remote/corba/TermData.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CorbaProvider.idl
* Thursday, November 16, 2000 1:38:18 o'clock PM EST
*/

public final class TermData implements org.omg.CORBA.portable.IDLEntity
{
  public String terminal = null;
  public boolean isMedia = false;

  public TermData ()
  {
  } // ctor      
  public TermData (String _terminal, boolean _isMedia)
  {
	terminal = _terminal;
	isMedia = _isMedia;
  } // ctor      
} // class TermData
